### ISSUE TITLE
Long Names Are Cut Off

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#34]
I noticed in the latest version, that a long name is not completely show and the text is cut off.

These are some words I've noticed to give examples. (Also 3 dots trail after the text like below)

Transmission - appears as > ```Transmissi...```

qtfm-6.0.1.tar.gz - appears as > ```qtfm-6.0.1....```

/usr/x86_64-slackware-linux - appears as > ```x86_64-sla...```

Numix Blue Slack.jpg - appears as > ```Numix Blu...```

**Comment by rodlie** [comment]
6.0 or 6.1?

**Comment by 0pLuS0** [comment]
I ran this yesterday and git pull today;

git clone https://github.com/rodlie/qtfm
cd qtfm
git checkout 6.0
git submodule update -i

**Comment by rodlie** [comment]
Ok, then it's not an regression :)

**Comment by rodlie** [comment]
Some progress on this feature, but I'm currently able to word-wrap filenames with space and -, but not others, seems to be a limitation somewhere, but will find a way around it somehow.

**Comment by 0pLuS0** [comment]
ok...

**Comment by rodlie** [comment]
This needs a custom item delegate to get working 100%, not sure I have the time to implement this for 6.1. I will look more into how to solve this next weekend, and (I hope) get it working before 6.1 is released.

**Comment by rodlie** [comment]
Preview:
![qtfm-view](https://user-images.githubusercontent.com/34516798/42717984-3797ed04-8705-11e8-9919-297b137384bc.png)

Looks ok?

**Comment by 0pLuS0** [comment]
Yeah the screen shot looks nice, now need to test in the Wild... LOL

Keep up the great work!

**Comment by rodlie** [comment]
More work is needed :) But it will be included in 6.1

**Comment by 0pLuS0** [comment]
Ok, sounds good...

One last thing, I know you have 2 branches and you mentioned the differences, but to be honest, at least at this point in time, I'm not seeing an difference when it comes to performance and stability between them, but Master Branch has better options. Personally Master branch just seems like the branch that should alread be released, not 6.0.x...

Hmm

**Comment by rodlie** [comment]
But master is not done, 6.1 beta will be released next week, final by the end of the month.

6.0 is the current stable until 6.1 is released.

**Comment by rodlie** [comment]
The next version should always be better than the previous :)

qtfm uses the following release cycle:

* when master is considered stable, branch master to 6.1, then release RC1
* when 6.1.0 is released the 6.1 branch is considered the stable branch, and should be used by end-users, this branch will only receive bugfixes, how long depends, usually only until the next 6.x release. The "old-stable" 6.0 branch is then considered deprecated.
* work continue on master (6.2), repeat ...

**Comment by 0pLuS0** [comment]
:+1:

**Comment by rodlie** [comment]
So, the UI modifications seems to work ok in qt5, but there are issues in qt4. Will try to fix qt4 tomorrow.

**Comment by 0pLuS0** [comment]
These were files as numbers, like;

001.jpg
002.jpg
003.jpg

And when I tried to change it, it just kept reverting back, I closed and reopened qtfm and it works now... odd

Something else I just found, when I click an image, I use ```Viewnior``` and it pops open saying;

```The given locations contain no images```

At the terminal I get this;

openInApp "/home/foo/Downloads/AEX Nougat Test.png" "" "image/png" "viewnior.desktop" "/usr/share/applications/viewnior.desktop" 
openInApp "viewnior %F" "/home/foo/Downloads/AEX Nougat Test.png" "" 
qprocess start detached "viewnior" "/home/foo/Downloads/AEX Nougat Test.png" 
running: "viewnior /home/rog/Downloads/AEX Nougat Test.png" 

(viewnior:4757): Gtk-CRITICAL **: IA__gtk_action_group_set_sensitive: assertion 'GTK_IS_ACTION_GROUP (action_group)' failed

Would you like a bug report for this?

Thanks

**Comment by rodlie** [comment]
I see the problem (regarding viewnior), will check the code.

**Comment by 0pLuS0** [comment]
Should I delete the above reply and make it into an ```Issue`` for your tracking?

**Comment by rodlie** [comment]
fix for openInApp is now in master.

**Comment by 0pLuS0** [comment]
You are a Hacking Mad Man! WoOt

**Comment by 0pLuS0** [comment]
Images working now... :+1:

**Comment by rodlie** [comment]
see #39 for open issues for this feature.

Should be fixed:
* highlight
* spacing

**Comment by 0pLuS0** [comment]
Long names is effecting the gaps?

**Comment by rodlie** [comment]
The view is based on a grid, I added spacing on the grid without checking for filename size, so the spacing is static and large. Will add a check for filename size and adjust the grid size according to the largest filename.

**Comment by 0pLuS0** [comment]
Sorry, you want me to make replies here for the Rename?

Sorry about the Bug report, I thought it was best to keep that different from this...

Anyhow, from what I read, I thought you pushed a fix for the renaming, but I still see it the same, color highlighted around the entire folder or image...


![qtfm_1](https://user-images.githubusercontent.com/36190223/42724896-540770e4-876a-11e8-9596-bda45bff399c.jpg)


![qtfm_2](https://user-images.githubusercontent.com/36190223/42724897-589cd14e-876a-11e8-9a6a-24476bcb3c1e.jpg)

**Comment by 0pLuS0** [comment]
I noticed you just added a fix, not sure if this was completed, or you are still working on it, but I am seeing the same thing, but not as bad. Hightlighting still happening around folders and images, more highlight around folders, and a slight border look of color around the text of images.



![rename_ 1](https://user-images.githubusercontent.com/36190223/42728877-80520eb6-87b5-11e8-900f-8126f595a1d0.jpg)


![rename_ 2](https://user-images.githubusercontent.com/36190223/42728880-848e9058-87b5-11e8-97cc-8c55b7a792a0.jpg)

**Comment by rodlie** [comment]
Yeah, I'm not done yet. Will probably be some commits until I get it right.

**Comment by 0pLuS0** [comment]
Ahh ok sorry, I jumped to soon, you know I'm just so excited! LOL

**Comment by rodlie** [comment]
Adding stuff so I don't forget:

* Text alignment is not perfect
* needs outer padding
* fix qt4 issues

**Comment by rodlie** [comment]
Most issues should now be resolved (may need some minor tweaks).

**Comment by 0pLuS0** [comment]
@rodlie hey there!

Yeah looking nicer, here's some issues I'm seeing.

1. After I make a change in the settings I see this at the terminal;
```link outline hasn't been detected!```

2. When clicking on a directory I noticed they all shift in the direction left or right. If you need a video I can make one to show you. Explained another way, say your in HOME, and click on a directory called ```Pictures``` and in Pictures there are like 10 directories. When clicking on Pictures, I'll notice all the directories as an example move slightly to the left real quick, for a split second. Then if I click on ```Home``` in the left Pane, all the directories in the Home, shift quickly for a split second to the right.

3. When right clicking an icon to rename it, can you please make the hightlight a little wider and taller around the words? It's a little bunched up at the moment. I'm attaching 2 screens, one qtfm and spacefm to show you the differences. SpaceFM in the screen shot might be hard to see, but if you look closely you can see it is bigger, and it's easier to tell in person looking at it.


```QTFM```

![qtfm](https://user-images.githubusercontent.com/36190223/43041243-db9f7346-8d49-11e8-8205-47fc87810c17.jpg)



```SpaceFM```

![spacefm](https://user-images.githubusercontent.com/36190223/43041246-e5c2c0d0-8d49-11e8-93e4-d32af67b07fc.jpg)


Keep up the great work! :)

**Comment by 0pLuS0** [comment]
@rodlie hey there!

Yeah looking nicer, here's some issues I'm seeing.

1. After I make a change in the settings I see this at the terminal;
```link outline hasn't been detected!```

2. When clicking on a directory I noticed they all shift in the direction left or right. If you need a video I can make one to show you. Explained another way, say your in HOME, and click on a directory called ```Pictures``` and in Pictures there are like 10 directories. When clicking on Pictures, I'll notice all the directories as an example move slightly to the left real quick, for a split second. Then if I click on ```Home``` in the left Pane, all the directories in the Home, shift quickly for a split second to the right.

3. Also the gap, distance between the directories changes when you move from one to another. Sometimes I seen the move farther apart, then at other times move closer together.

$. When right clicking an icon to rename it, can you please make the hightlight a little wider and taller around the words? It's a little bunched up at the moment. I'm attaching 2 screens, one qtfm and spacefm to show you the differences. SpaceFM in the screen shot might be hard to see, but if you look closely you can see it is bigger, and it's easier to tell in person looking at it.


```QTFM```

![qtfm](https://user-images.githubusercontent.com/36190223/43041243-db9f7346-8d49-11e8-8205-47fc87810c17.jpg)



```SpaceFM```

![spacefm](https://user-images.githubusercontent.com/36190223/43041246-e5c2c0d0-8d49-11e8-93e4-d32af67b07fc.jpg)


Keep up the great work! :)

**Comment by 0pLuS0** [comment]
@rodlie hey there!

Yeah looking nicer, here's some issues I'm seeing.

1. After I make a change in the settings I see this at the terminal;
```link outline hasn't been detected!```

2. When clicking on a directory I noticed they all shift in the direction left or right. If you need a video I can make one to show you. Explained another way, say your in HOME, and click on a directory called ```Pictures``` and in Pictures there are like 10 directories. When clicking on Pictures, I'll notice all the directories as an example move slightly to the left real quick, for a split second. Then if I click on ```Home``` in the left Pane, all the directories in the Home, shift quickly for a split second to the right.

3. Also the gap, distance between the directories changes when you move from one to another. Sometimes I seen the move farther apart, then at other times move closer together.

4. When right clicking an icon to rename it, can you please make the hightlight a little wider and taller around the words? It's a little bunched up at the moment. I'm attaching 2 screens, one qtfm and spacefm to show you the differences. SpaceFM in the screen shot might be hard to see, but if you look closely you can see it is bigger, and it's easier to tell in person looking at it.


```QTFM```

![qtfm](https://user-images.githubusercontent.com/36190223/43041243-db9f7346-8d49-11e8-8205-47fc87810c17.jpg)



```SpaceFM```

![spacefm](https://user-images.githubusercontent.com/36190223/43041246-e5c2c0d0-8d49-11e8-93e4-d32af67b07fc.jpg)


Keep up the great work! :)

**Comment by rodlie** [comment]
1. This is a issue with an SVG somewhere (.desktop from qt maybe?). This is out of my control.
2. I know, I need to refresh the "grid" to align stuff because of the length of the file names, unsure if I can fix this any better
3. A bit unsure what you mean
4. This is controlled by Qt, and needs to be overridden (somewhere). Will check.

**Comment by 0pLuS0** [comment]
1. Hmm
2. Well you don't want the directories shifting around, you don't want to leave it like this.
3. The gap between the directories going ```left <----> right``` they go back and forth, close together, then spread out wider, as with issue 2, moving left and right all of them, these both happen at the same time. 
4. Ok...

**Comment by 0pLuS0** [comment]
1. Hmm
2. Well you don't want the directories shifting around, you don't want to leave it like this.
3. The gap between the directories going ```left <----> right``` they go back and forth, close together, then spread out wider, as with issue 2, moving left and right all of them, these both happen at the same time. 
4. Ok...

I forgot to ask, with the dracolinux.org domain, you are part of the development? Seems like there hasn't been anything doing on with  dracolinux in years...

**Comment by rodlie** [comment]
> Well you don't want the directories shifting around, you don't want to leave it like this.

I need to adjust based on filename, currently this is it.

> The gap between the directories going left <----> right they go back and forth, close together, then spread out wider, as with issue 2, moving left and right all of them, these both happen at the same time.

This is the same as 2. I adjust the grid based on filename. The longest filename decides the minimum width.

> I forgot to ask, with the dracolinux.org domain, you are part of the development? Seems like there hasn't been anything doing on with dracolinux in years...

I am Draco. I don't have time working on it anymore, maybe in the future .....

**Comment by rodlie** [comment]
https://github.com/rodlie/qtfm/commit/8b60d38620dd7e394df90c8283f1d633925b4094 should fix .2

**Comment by rodlie** [comment]
The width is now static, so items should not move.

**Comment by 0pLuS0** [comment]
Hey,

If I'm jumping to much ahead here on the Master Branch in regards to submitting issues, please let me know? I mean, I keep forgetting, hehe, that you are still working on it, and wondering if I should just wait some period of time before reporting anything, or anything I find as of now you'd like to know?

**Comment by rodlie** [comment]
Major modifications/features will not be worked on until 6.1 is done. I will release 6.1 beta on Monday, then use the rest of this month to fix bugs (in 6.1). Feel free to add issues, but note that they might  not be worked on for a while.

**Comment by 0pLuS0** [comment]
Oh sure, I know how it works, I just got all excited forgetting...

Anyhow with regards to the ```link outline hasn't been detected!``` this only appears in the ```Settings``` when I make any change, then I get this message.

I noticed when I go into a / root directory, maybe because there are a lot of directories under it, like in /etc when I click /etc it takes like 2-3 seconds to open, there's a lag on opening a lot of directories.

Also now the directories move up and down slightly when changing from one to another, no more left & right movement... :)

On the subject again over directories, name lengths are being not cut off, but showing like this now as example;

ScreenShot
s

The s appears under the n center...

I looked through SpaceFM and of course with long names it does the same thing, but it's allowing more characters to appear before getting cut off, so of course I don't really know how this works, but let me give you some ideas of SpaceFM vs QtFM...

SpaceFM
/var/log/
removed_packag
es

/var/log/removed_scripts (appears all on one line)


QtFM
/var/log
removed_pa
ckages

/var/log/
removed_sc
ripts

**Comment by rodlie** [comment]
> Anyhow with regards to the link outline hasn't been detected! this only appears in the Settings when I make any change, then I get this message.

I removed png/svg warnings for qt5, can't do anything with qt4.

> Also now the directories move up and down slightly when changing from one to another, no more left & right movement... :)

Something have to move :) The grid is dynamic and has to either base it's size on width or height. The grid is static width x largest height.

> I looked through SpaceFM and of course with long names it does the same thing, but it's allowing more characters to appear before getting cut off, so of course I don't really know how this works, but let me give you some ideas of SpaceFM vs QtFM...

I set a static width and the text is wrapped when it is larger than the width, how am I suppose to know where to wrap the text?

> I noticed when I go into a / root directory, maybe because there are a lot of directories under it, like in /etc when I click /etc it takes like 2-3 seconds to open, there's a lag on opening a lot of directories.

I don't notice anything, are you running a regular HDD?

Also note, the more features I add or the more stuff I do in the paint function the slower things will go. If 6.1 is not slower than 6.0 it's a win ;)

**Comment by rodlie** [comment]
I will try to get the wrapping better.

You have a much faster machine than me (I develop on a laptop with an i5-2520m & a random Kingston low-end SSD). Maybe test qt5? I noticed that resizing the window in qt4 is slow, while on qt5 it's smooth.

**Comment by rodlie** [comment]
Since the original issue has been added to qtfm I renamed this issue.

**Comment by 0pLuS0** [comment]
:+1:

**Comment by rodlie** [comment]
So, back to word wrap.

If you want static width then the word wrap stay as-is, if you want "smart" word wrap then the width need to be dynamic as well.

**Comment by 0pLuS0** [comment]
Hey I'm just an End-User Man! hehe

You the Coder-Man, so I have no idea how it works, all I know is within all my years in Linux and the mass amount of times over these years I've used various file managers, all of them have the distance, width, whatever is it, remain, and look clean...

It's up to you! :)

**Comment by 0pLuS0** [comment]
@rodlie Congrats on the 6.1.0 release! It's looking nice.

I wasn't sure if on this release, or in the future, but I wanted to let you know, I still see the directories shifting around slightly when moving around through them, but not as bad before. I compiled against qt-4.8.7.

Keep up the great work!

**Comment by rodlie** [comment]
I know, I tried to make it better than it was, but it's not perfect. I will try to fix this for 6.2, and if possible backport to 6.1.

I'm a bit busy with other project this month, but will continue on 6.2 by the end of this month (critical issues in 6.1 will be fixed when reported/found).

6.2 will feature some major changes to get issue #31 working, and will probably take most of next month to get stable/ustable.

Btw, qtfm 6.1.x will be available in the next SlackBuilds update (https://slackbuilds.org/ready/).

**Comment by rodlie** [comment]
Yeah, there are several UI tweaks that are needed.

New development has stalled a bit, mostly due to the amount of bugs found in 6.1. The 6.1 branch (as of 6.1.5) seems stable now, so I will start work on 6.2 soon.

Highest priority is a proper file copy/move dialog with support for multiple instances. Then I will add the remaining open issues for 6.2.

I would like to get NetBSD and macOS (if possible, at least as a "tech-preview") support in 6.2.

Major changes will have to wait until v7 (I will re-write the main GUI).

I'm currently busy with another project, but will try to get most things done before the end of 2018.

**Comment by 0pLuS0** [comment]
Haven't played with qtfm in ages, if I get some time I'll play again...

**Comment by rodlie** [comment]
@0pLuS0 : We are still at 6.1, so not that much to test (if you find bugs great). Major changes will not happen until v7, since I need to get rid of a lot of "legacy" code to implement the remaining feature requests. Sadly I have limited time to dedicate to this project...

**Comment by imrn** [comment]
Well, this may be off topic but distruptions can be productive in unexpected ways.

@rodlie: Did you ever think about building a qt "panel" application such as tint2,
lxqt4-panel, xfce4-panel, etc? You may wonder why I've made such a suggestion.

Applications/mimes (that are already related with many issues on qtfm) are
also related with a panel's application menu. I'd admit that, they are not
directly related but a satisfying and customizable application access is still
missing from the linux desktop. I think problem is a close relative of the
app/mime issues for the fm.

Given that you've already have https://github.com/rodlie/powerkit in the
notifications area and my issue #100, I would say you are already in navigating in
desktop waters. (Additionally, I only have the clock, window buttons as extras on
my panel.)

If you find this post useful and want to keep it around as a seperate issue or even a
new project I'd happily want to participate in that.

**Comment by rodlie** [comment]
I currently use tint2 as panel and it works great for my use, creating "another" panel is not something I have planned, but I'm open for suggestions.

**Comment by imrn** [comment]
Ok then. First things first: I'd be happy to see qtfm having a fine
applications/mimes/desktop management functionalities first.

Now, let me paint a futuristic/bloated desktop fm picture here: ;)
- Customizable Buttons: May be in the form of a tree.
- A menu and/or bar and/or side panel showing child processes
launched via double clicks, sendto context menu, clicking on
custom buttons or dragging files/dirs on them.
- Ability to manage/minimize/maximize child processes.
