### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by rodlie** [rodlie/qtfm#89]
Initial support was added in https://github.com/rodlie/qtfm/pull/82 by @Tatsh, but needs more work.

Use this issue to track progress.

**Comment by rodlie** [comment]
done.

**Comment by rodlie** [comment]
@Tatsh : Could you please test https://github.com/rodlie/qtfm/releases/download/6.1.6-rc1/qtfm-6.1.6-rc1.dmg . I was not able to fix my old macbook so I'm borrowing one for a very limited time, so please report any bugs while I got access to macOS ;)

Built on 10.11 for 10.7. Uses static Qt 5.6 (last version that supports 10.7) built against latest zlib,libpng,jpegsrc. macports etc not needed.

Travis CI will build and deploy the DMG on tags so I don't need test/build it manually on macOS before every release.

**Comment by Tatsh** [comment]
Seems to work, but do we have to be stuck with Adwaita theme? I don't mind that much but I liked how the Mac theme looked. Also, I don't see why this shouldn't be customisable even on macOS.

Most files still don't have an icon. Apps now show their correct icon and open correctly. MP3 files get an audio icon, but m4a files do not. Text file types also have no icon.
